name: Trigger Training Job

on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types: [completed]
  workflow_dispatch:


jobs:
  trigger-training:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Get PR SHA
        id: get-sha
        run: |
          SHA="${{ github.event.workflow_run.head_sha }}"
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "Using SHA: $SHA"
          
      - name: Trigger API Training Job
        run: |
          curl -X POST http://localhost:8000/train \
            -H "Content-Type: application/json" \
            -d '{
              "pr": "${{ github.event.workflow_run.pull_requests[0].number }}",
              "repo": "${{ github.repository }}",
              "sha": "${{ steps.get-sha.outputs.sha }}",
              "image": "fdgdfgdgf123/train-img:${{ steps.get-sha.outputs.sha }}",
              "params": {
                "epochs": 5,
                "batch_size": 4,
                "lr": 0.001
              }
            }'
